"""
AnimateDiff Inference Module for Video Generation

AnimateDiff adds motion to static images generated by Stable Diffusion.
Works with SDXL (recommended) or SD 1.5 for generating animated videos.
"""
import torch
import os
import time
import numpy as np
from PIL import Image
from diffusers import (
    StableDiffusionXLPipeline, 
    StableDiffusionPipeline,
    EulerDiscreteScheduler,
    MotionAdapter
)
from diffusers.utils import export_to_video
from typing import Optional, Tuple

# Model cache
_sdxl_pipe = None
_sd15_pipe = None
_motion_adapter = None

# Available AnimateDiff models
ANIMEDIFF_MODELS = {
    "sdxl": {
        "base": "stabilityai/stable-diffusion-xl-base-1.0",
        "motion": "guoyww/animatediff-sdxl-lightning",  # Fast motion model
    },
    "sd15": {
        "base": "runwayml/stable-diffusion-v1-5",
        "motion": "guoyww/animatediff-motion-adapter-v1-5-2",  # SD1.5 motion
    },
    "sdxl Lightning": {
        "base": "stabilityai/stable-diffusion-xl-base-1.0",
        "motion": "guoyww/animatediff-sdxl-lightning",
    },
}


def load_motion_adapter(motion_model: str = "sdxl"):
    """Load AnimateDiff motion adapter"""
    global _motion_adapter
    
    if _motion_adapter is not None:
        return _motion_adapter
    
    model_config = ANIMEDIFF_MODELS.get(motion_model, ANIMEDIFF_MODELS["sdxl"])
    motion_path = model_config["motion"]
    
    print(f"📥 Loading AnimateDiff Motion Adapter: {motion_path}", flush=True)
    
    _motion_adapter = MotionAdapter.from_pretrained(
        motion_path,
        torch_dtype=torch.float16
    ).to("cuda")
    
    print("✅ AnimateDiff Motion Adapter loaded", flush=True)
    return _motion_adapter


def load_sdxl_animatediff():
    """Load SDXL with AnimateDiff (recommended for quality)"""
    global _sdxl_pipe
    
    if _sdxl_pipe is not None:
        return _sdxl_pipe
    
    from diffusers import AutoPipelineForText2Image
    
    print("📥 Loading SDXL + AnimateDiff...", flush=True)
    
    # Load motion adapter
    motion_adapter = load_motion_adapter("sdxl")
    
    # Create pipeline with motion
    pipe = AutoPipelineForText2Image.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0",
        torch_dtype=torch.float16,
        variant="fp16"
    )
    
    # Load motion adapter into pipeline
    pipe.motion_adapter = motion_adapter
    
    # Enable GPU
    pipe = pipe.to("cuda")
    
    # Set scheduler for better results
    pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)
    
    # Enable memory optimizations
    pipe.enable_vae_slicing()
    pipe.enable_vae_tiling()
    
    _sdxl_pipe = pipe
    print("✅ SDXL + AnimateDiff loaded successfully", flush=True)
    return _sdxl_pipe


def load_sd15_animatediff():
    """Load SD 1.5 with AnimateDiff (faster, less VRAM)"""
    global _sd15_pipe
    
    if _sd15_pipe is not None:
        return _sd15_pipe
    
    from diffusers import AutoPipelineForText2Image
    
    print("📥 Loading SD 1.5 + AnimateDiff...", flush=True)
    
    # Load motion adapter
    motion_adapter = load_motion_adapter("sd15")
    
    # Create pipeline
    pipe = AutoPipelineForText2Image.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
        torch_dtype=torch.float16,
        variant="fp16"
    )
    
    # Attach motion adapter
    pipe.motion_adapter = motion_adapter
    
    pipe = pipe.to("cuda")
    pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)
    
    pipe.enable_vae_slicing()
    
    _sd15_pipe = pipe
    print("✅ SD 1.5 + AnimateDiff loaded successfully", flush=True)
    return _sd15_pipe


def generate_animatediff_video(
    prompt: str,
    negative_prompt: str = "",
    num_frames: int = 16,
    num_inference_steps: int = 25,
    guidance_scale: float = 7.5,
    height: int = 1024,
    width: int = 1024,
    model_type: str = "sdxl",  # "sdxl" or "sd15"
    output_dir: str = "/workspace/remote_ai_group/outputs"
) -> Tuple[str, str]:
    """
    Generate animated video using AnimateDiff
    
    Args:
        prompt: Text description
        negative_prompt: What to avoid
        num_frames: Number of frames to generate (8, 16, 24, 32)
        num_inference_steps: Quality vs speed
        guidance_scale: Prompt adherence
        height/width: Resolution (SDXL: 1024x1024, SD15: 512x512)
        model_type: "sdxl" (quality) or "sd15" (faster)
    """
    print(f"🎬 AnimateDiff: '{prompt[:50]}...' ({model_type})", flush=True)
    start_time = time.time()
    
    # Select model
    if model_type == "sdxl":
        pipe = load_sdxl_animatediff()
        if height > 1024:
            height = 1024
        if width > 1024:
            width = 1024
    else:
        pipe = load_sd15_animatediff()
        # SD15 works better at 512x512
        if height > 512:
            height = 512
        if width > 512:
            width = 512
    
    # Generate
    with torch.inference_mode():
        output = pipe(
            prompt=prompt,
            negative_prompt=negative_prompt,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            height=height,
            width=width,
            num_frames=num_frames,
        )
    
    # Extract frames
    frames = output.frames[0] if hasattr(output, 'frames') else output.images
    
    # Save as video
    job_id = f"ad_{model_type}_{int(time.time())}"
    output_path = os.path.join(output_dir, f"{job_id}.mp4")
    os.makedirs(output_dir, exist_ok=True)
    
    export_to_video(frames, output_video_path=output_path, fps=8)
    
    elapsed = time.time() - start_time
    print(f"✅ Generated {job_id}.mp4 ({num_frames} frames) in {elapsed:.1f}s", flush=True)
    
    return job_id, output_path


def generate_from_image_animatediff(
    image_path: str,
    prompt: str = "",
    negative_prompt: str = "",
    num_frames: int = 16,
    num_inference_steps: int = 20,
    guidance_scale: float = 7.5,
    strength: float = 0.8,
    output_dir: str = "/workspace/remote_ai_group/outputs"
) -> Tuple[str, str]:
    """
    Animate a static image using AnimateDiff
    
    Args:
        image_path: Path to input image
        prompt: Motion description (e.g., "walking, left to right")
        negative_prompt: What to avoid
        num_frames: Number of frames
        strength: How much to transform the image (0-1)
    """
    print(f"🎬 AnimateDiff Image Animation: {image_path}", flush=True)
    start_time = time.time()
    
    # Load image
    init_image = Image.open(image_path).convert("RGB")
    
    # Resize for SDXL
    init_image = init_image.resize((1024, 1024))
    
    pipe = load_sdxl_animatediff()
    
    with torch.inference_mode():
        output = pipe(
            prompt=prompt,
            image=init_image,
            negative_prompt=negative_prompt,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            strength=strength,
            num_frames=num_frames,
        )
    
    frames = output.frames[0] if hasattr(output, 'frames') else output.images
    
    job_id = f"ad_img_{int(time.time())}"
    output_path = os.path.join(output_dir, f"{job_id}.mp4")
    os.makedirs(output_dir, exist_ok=True)
    
    export_to_video(frames, output_video_path=output_path, fps=8)
    
    elapsed = time.time() - start_time
    print(f"✅ Generated animated video in {elapsed:.1f}s", flush=True)
    
    return job_id, output_path
