import pytest
from src.services.optimization.aeo_service import base_aeo_service, AEOAnalysisResult


def test_base_aeo_service_analysis():
    title = "How to Automate Viral Short Videos with AI in 2026"
    script = (
        "Here is how you can scale your video production by 500% using Python and Remotion. "
        "First, we scan TikTok and YouTube for high-retention audio. Then, we synthesize scripts "
        "using OpenAI and Claude. Over $10,000 in monthly ad revenue was generated by creators using this system. "
        "Why does this work so effectively? Because automated editing cuts latency by 85%."
    )

    result = base_aeo_service.analyze_and_optimize(
        title=title,
        script_or_transcript=script,
        niche="AI Automation",
        target_platform="youtube",
    )

    assert isinstance(result, AEOAnalysisResult)
    assert result.scores.overall_aeo_score > 0
    assert result.scores.direct_answer_score == 90.0
    assert len(result.extracted_entities) > 0
    assert "Python" in result.extracted_entities or "Remotion" in result.extracted_entities
    assert len(result.identified_claims) > 0
    assert result.json_ld_schema["@type"] == "VideoObject"
    assert len(result.optimized_faq_pairs) >= 1
