blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/psalmprax/ettametta#readme
    about: Check the README before opening an issue
  - name: Discussions
    url: https://github.com/psalmprax/ettametta/discussions
    about: Please ask questions and start discussions here
