"""add_credit_system_tables

Revision ID: 260bae1bf65b
Revises: efb25ef5b164
Create Date: 2026-04-24 05:41:08.976711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260bae1bf65b'
down_revision: Union[str, Sequence[str], None] = 'efb25ef5b164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_packages_id'), 'credit_packages', ['id'], unique=False)
    op.create_table('credit_usage_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('credits_required', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tier_required', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_usage_rules_action'), 'credit_usage_rules', ['action'], unique=True)
    op.create_index(op.f('ix_credit_usage_rules_id'), 'credit_usage_rules', ['id'], unique=False)
    op.create_table('subscription_credits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('monthly_credits', sa.Integer(), nullable=True),
    sa.Column('rollover_enabled', sa.Boolean(), nullable=True),
    sa.Column('max_rollover', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_credits_id'), 'subscription_credits', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_credits_tier'), 'subscription_credits', ['tier'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=True),
    sa.Column('referred_id', sa.String(length=36), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reward_credits', sa.Integer(), nullable=True),
    sa.Column('reward_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('user_credits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('lifetime_purchased', sa.Integer(), nullable=True),
    sa.Column('lifetime_earned', sa.Integer(), nullable=True),
    sa.Column('lifetime_spent', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credits_id'), 'user_credits', ['id'], unique=False)
    op.create_index(op.f('ix_user_credits_user_id'), 'user_credits', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credits_user_id'), table_name='user_credits')
    op.drop_index(op.f('ix_user_credits_id'), table_name='user_credits')
    op.drop_table('user_credits')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_subscription_credits_tier'), table_name='subscription_credits')
    op.drop_index(op.f('ix_subscription_credits_id'), table_name='subscription_credits')
    op.drop_table('subscription_credits')
    op.drop_index(op.f('ix_credit_usage_rules_id'), table_name='credit_usage_rules')
    op.drop_index(op.f('ix_credit_usage_rules_action'), table_name='credit_usage_rules')
    op.drop_table('credit_usage_rules')
    op.drop_index(op.f('ix_credit_packages_id'), table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
