"""Add metrics to PublishedContentDB

Revision ID: 2aa1c8c2bf49
Revises: 86ebe6287aea
Create Date: 2026-02-15 13:13:19.931476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa1c8c2bf49'
down_revision: Union[str, Sequence[str], None] = '86ebe6287aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_content', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('published_content', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('published_content', sa.Column('shares', sa.Integer(), nullable=True))
    op.add_column('published_content', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('published_content', sa.Column('retention_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_content', 'retention_rate')
    op.drop_column('published_content', 'comments')
    op.drop_column('published_content', 'shares')
    op.drop_column('published_content', 'likes')
    op.drop_column('published_content', 'view_count')
    # ### end Alembic commands ###
