"""Add metrics to PublishedContentDB

Revision ID: 86ebe6287aea
Revises: a4b1aaadd072
Create Date: 2026-02-15 13:09:31.338953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ebe6287aea'
down_revision: Union[str, Sequence[str], None] = 'a4b1aaadd072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_content', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_published_content_user_id'), 'published_content', ['user_id'], unique=False)
    op.create_foreign_key(None, 'published_content', 'users', ['user_id'], ['id'])
    op.add_column('social_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'social_accounts', 'users', ['user_id'], ['id'])
    op.add_column('video_jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_video_jobs_user_id'), 'video_jobs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'video_jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_video_jobs_user_id'), table_name='video_jobs')
    op.drop_column('video_jobs', 'user_id')
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_column('social_accounts', 'user_id')
    op.drop_constraint(None, 'published_content', type_='foreignkey')
    op.drop_index(op.f('ix_published_content_user_id'), table_name='published_content')
    op.drop_column('published_content', 'user_id')
    # ### end Alembic commands ###
