"""Add user_id to affiliate_links

Revision ID: a1b2c3d4e5f
Revises: 65439aa3c71f
Create Date: 2026-03-31 14:20:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f"
down_revision: Union[str, Sequence[str], None] = "65439aa3c71f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("affiliate_links", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_affiliate_links_user_id"), "affiliate_links", ["user_id"], unique=False
    )
    op.create_foreign_key(None, "affiliate_links", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "affiliate_links", type_="foreignkey")
    op.drop_index(op.f("ix_affiliate_links_user_id"), table_name="affiliate_links")
    op.drop_column("affiliate_links", "user_id")
    # ### end Alembic commands ###
