"""initial migration

Revision ID: a4b1aaadd072
Revises: 
Create Date: 2026-02-15 02:20:01.198161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a4b1aaadd072'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.drop_index(op.f('ix_viral_patterns_content_id'), table_name='viral_patterns')
    op.drop_index(op.f('ix_viral_patterns_id'), table_name='viral_patterns')
    op.drop_table('viral_patterns')
    op.add_column('content_candidates', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('author', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('title', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('description', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('engagement_rate', sa.Float(), nullable=True))
    op.add_column('content_candidates', sa.Column('discovery_date', sa.DateTime(), nullable=True))
    op.add_column('content_candidates', sa.Column('tags', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_content_candidates_niche'), table_name='content_candidates')
    op.drop_column('content_candidates', 'found_at')
    op.drop_column('content_candidates', 'velocity')
    op.drop_column('content_candidates', 'niche')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_candidates', sa.Column('niche', sa.VARCHAR(), nullable=True))
    op.add_column('content_candidates', sa.Column('velocity', sa.FLOAT(), nullable=True))
    op.add_column('content_candidates', sa.Column('found_at', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_content_candidates_niche'), 'content_candidates', ['niche'], unique=False)
    op.drop_column('content_candidates', 'tags')
    op.drop_column('content_candidates', 'discovery_date')
    op.drop_column('content_candidates', 'engagement_rate')
    op.drop_column('content_candidates', 'description')
    op.drop_column('content_candidates', 'title')
    op.drop_column('content_candidates', 'author')
    op.drop_column('content_candidates', 'platform')
    op.create_table('viral_patterns',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('content_id', sa.VARCHAR(), nullable=True),
    sa.Column('hook_score', sa.FLOAT(), nullable=True),
    sa.Column('retention_estimate', sa.FLOAT(), nullable=True),
    sa.Column('pacing_bpm', sa.INTEGER(), nullable=True),
    sa.Column('style_keywords', sqlite.JSON(), nullable=True),
    sa.Column('emotional_triggers', sqlite.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_patterns_id'), 'viral_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_viral_patterns_content_id'), 'viral_patterns', ['content_id'], unique=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
