"""Add AB testing and scheduling tables

Revision ID: b00605d117b1
Revises: 2aa1c8c2bf49
Create Date: 2026-02-16 00:40:41.753645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00605d117b1'
down_revision: Union[str, Sequence[str], None] = '2aa1c8c2bf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
