"""align_production_schema

Revision ID: d410fb0d40a9
Revises: g1b2c3d4e5f7
Create Date: 2026-05-01 06:58:17.130204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd410fb0d40a9'
down_revision: Union[str, Sequence[str], None] = 'g1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_zero_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_agent_zero_state_key'), 'agent_zero_state', ['key'], unique=False)
    op.create_table('lead_gen_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('niche', sa.String(), nullable=True),
    sa.Column('form_uri', sa.String(), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_gen_configs_id'), 'lead_gen_configs', ['id'], unique=False)
    op.create_index(op.f('ix_lead_gen_configs_niche'), 'lead_gen_configs', ['niche'], unique=False)
    op.create_index(op.f('ix_lead_gen_configs_user_id'), 'lead_gen_configs', ['user_id'], unique=False)
    op.add_column('content_candidates', sa.Column('source_uri', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('thumbnail_uri', sa.String(), nullable=True))
    op.drop_column('content_candidates', 'source_url')
    op.drop_column('content_candidates', 'thumbnail_url')
    op.add_column('digital_products', sa.Column('purchase_uri', sa.String(), nullable=True))
    op.drop_column('digital_products', 'purchase_url')
    op.add_column('incident_webhooks', sa.Column('uri', sa.String(), nullable=False))
    op.drop_column('incident_webhooks', 'url')
    op.add_column('membership_plans', sa.Column('sign_up_uri', sa.String(), nullable=True))
    op.add_column('membership_plans', sa.Column('cta_text', sa.String(), nullable=True))
    op.drop_column('membership_plans', 'sign_up_url')
    op.add_column('nexus_jobs', sa.Column('current_node', sa.String(), nullable=True))
    op.add_column('nexus_jobs', sa.Column('node_status', sa.JSON(), nullable=True))
    op.add_column('nexus_jobs', sa.Column('job_metadata', sa.JSON(), nullable=True))
    op.add_column('nexus_jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('personas', sa.Column('reference_image_uri', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('reference_video_uri', sa.String(), nullable=True))
    op.drop_column('personas', 'reference_video_url')
    op.drop_column('personas', 'reference_image_url')
    op.add_column('published_content', sa.Column('source_uri', sa.String(), nullable=True))
    op.drop_column('published_content', 'source_url')
    op.add_column('video_jobs', sa.Column('source_uri', sa.String(), nullable=True))
    op.drop_column('video_jobs', 'source_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('video_jobs', 'source_uri')
    op.add_column('published_content', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('published_content', 'source_uri')
    op.add_column('personas', sa.Column('reference_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personas', sa.Column('reference_video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('personas', 'reference_video_uri')
    op.drop_column('personas', 'reference_image_uri')
    op.drop_column('nexus_jobs', 'updated_at')
    op.drop_column('nexus_jobs', 'job_metadata')
    op.drop_column('nexus_jobs', 'node_status')
    op.drop_column('nexus_jobs', 'current_node')
    op.add_column('membership_plans', sa.Column('sign_up_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('membership_plans', 'cta_text')
    op.drop_column('membership_plans', 'sign_up_uri')
    op.add_column('incident_webhooks', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('incident_webhooks', 'uri')
    op.add_column('digital_products', sa.Column('purchase_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('digital_products', 'purchase_uri')
    op.add_column('content_candidates', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('content_candidates', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('content_candidates', 'thumbnail_uri')
    op.drop_column('content_candidates', 'source_uri')
    op.drop_index(op.f('ix_lead_gen_configs_user_id'), table_name='lead_gen_configs')
    op.drop_index(op.f('ix_lead_gen_configs_niche'), table_name='lead_gen_configs')
    op.drop_index(op.f('ix_lead_gen_configs_id'), table_name='lead_gen_configs')
    op.drop_table('lead_gen_configs')
    op.drop_index(op.f('ix_agent_zero_state_key'), table_name='agent_zero_state')
    op.drop_table('agent_zero_state')
    # ### end Alembic commands ###
