"""add_scheduled_posts_columns_phase_6

Revision ID: ee8627d8341b
Revises: merge_heads_2026
Create Date: 2026-04-17 16:50:02.050374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee8627d8341b'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_2026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('predicted_retention', sa.Float(), nullable=True),
    sa.Column('actual_retention', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_history_id'), 'drift_history', ['id'], unique=False)
    op.create_table('experiment_cohorts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_cohorts_id'), 'experiment_cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_experiment_cohorts_strategy'), 'experiment_cohorts', ['strategy'], unique=False)
    op.create_table('self_healing_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('exception_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_healing_audits_id'), 'self_healing_audits', ['id'], unique=False)
    op.create_index(op.f('ix_self_healing_audits_path'), 'self_healing_audits', ['path'], unique=False)
    op.create_table('strategy_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_registry_id'), 'strategy_registry', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_registry_name'), 'strategy_registry', ['name'], unique=True)
    op.create_table('trading_watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uix_trading_user_symbol')
    )
    op.create_index(op.f('ix_trading_watchlists_id'), 'trading_watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_trading_watchlists_symbol'), 'trading_watchlists', ['symbol'], unique=False)
    op.create_index(op.f('ix_trading_watchlists_user_id'), 'trading_watchlists', ['user_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.Column('avg_duration', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['published_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_content_id'), 'performance_snapshots', ['content_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_id'), 'performance_snapshots', ['id'], unique=False)
    op.drop_index(op.f('ix_credit_packages_id'), table_name='credit_packages')
    op.drop_table('credit_packages')
    op.drop_index(op.f('ix_user_credits_id'), table_name='user_credits')
    op.drop_index(op.f('ix_user_credits_user_id'), table_name='user_credits')
    op.drop_table('user_credits')
    op.drop_index(op.f('ix_subscription_credits_id'), table_name='subscription_credits')
    op.drop_index(op.f('ix_subscription_credits_tier'), table_name='subscription_credits')
    op.drop_table('subscription_credits')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_credit_usage_rules_action'), table_name='credit_usage_rules')
    op.drop_index(op.f('ix_credit_usage_rules_id'), table_name='credit_usage_rules')
    op.drop_table('credit_usage_rules')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.add_column('content_candidates', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('creator_name', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('creator_id', sa.String(), nullable=True))
    op.add_column('content_candidates', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('content_candidates', sa.Column('scanned_at', sa.DateTime(), nullable=True))
    op.add_column('content_candidates', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('content_candidates', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('content_candidates', sa.Column('share_count', sa.Integer(), nullable=True))
    op.add_column('content_candidates', sa.Column('analysis_results', sa.JSON(), nullable=True))
    op.add_column('content_candidates', sa.Column('analyzed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_content_candidates_external_id'), 'content_candidates', ['external_id'], unique=True)
    op.drop_column('content_candidates', 'author')
    op.add_column('scheduled_posts', sa.Column('parallel_allowed', sa.Boolean(), nullable=True))
    op.add_column('scheduled_posts', sa.Column('user_timezone', sa.String(length=50), nullable=True))
    op.add_column('scheduled_posts', sa.Column('engagement_prediction', sa.Float(), nullable=True))
    op.add_column('scheduled_posts', sa.Column('optimal_rank', sa.Integer(), nullable=True))
    op.add_column('scheduled_posts', sa.Column('last_retry_at', sa.DateTime(), nullable=True))
    op.add_column('video_jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'error_message')
    op.drop_column('scheduled_posts', 'last_retry_at')
    op.drop_column('scheduled_posts', 'optimal_rank')
    op.drop_column('scheduled_posts', 'engagement_prediction')
    op.drop_column('scheduled_posts', 'user_timezone')
    op.drop_column('scheduled_posts', 'parallel_allowed')
    op.add_column('content_candidates', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_content_candidates_external_id'), table_name='content_candidates')
    op.drop_column('content_candidates', 'analyzed_at')
    op.drop_column('content_candidates', 'analysis_results')
    op.drop_column('content_candidates', 'share_count')
    op.drop_column('content_candidates', 'comment_count')
    op.drop_column('content_candidates', 'like_count')
    op.drop_column('content_candidates', 'scanned_at')
    op.drop_column('content_candidates', 'published_at')
    op.drop_column('content_candidates', 'creator_id')
    op.drop_column('content_candidates', 'creator_name')
    op.drop_column('content_candidates', 'external_id')
    op.create_table('referrals',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('referrer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('referred_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reward_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reward_claimed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name=op.f('referrals_referred_id_fkey')),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('referrals_referrer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('referrals_pkey'))
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('credit_usage_rules',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('credits_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tier_required', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_usage_rules_pkey'))
    )
    op.create_index(op.f('ix_credit_usage_rules_id'), 'credit_usage_rules', ['id'], unique=False)
    op.create_index(op.f('ix_credit_usage_rules_action'), 'credit_usage_rules', ['action'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credit_transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_transactions_pkey'))
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_table('subscription_credits',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('monthly_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rollover_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_rollover', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_credits_pkey'))
    )
    op.create_index(op.f('ix_subscription_credits_tier'), 'subscription_credits', ['tier'], unique=True)
    op.create_index(op.f('ix_subscription_credits_id'), 'subscription_credits', ['id'], unique=False)
    op.create_table('user_credits',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifetime_purchased', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifetime_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifetime_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_credits_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_credits_pkey'))
    )
    op.create_index(op.f('ix_user_credits_user_id'), 'user_credits', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_credits_id'), 'user_credits', ['id'], unique=False)
    op.create_table('credit_packages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_packages_pkey'))
    )
    op.create_index(op.f('ix_credit_packages_id'), 'credit_packages', ['id'], unique=False)
    op.drop_index(op.f('ix_performance_snapshots_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_content_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_trading_watchlists_user_id'), table_name='trading_watchlists')
    op.drop_index(op.f('ix_trading_watchlists_symbol'), table_name='trading_watchlists')
    op.drop_index(op.f('ix_trading_watchlists_id'), table_name='trading_watchlists')
    op.drop_table('trading_watchlists')
    op.drop_index(op.f('ix_strategy_registry_name'), table_name='strategy_registry')
    op.drop_index(op.f('ix_strategy_registry_id'), table_name='strategy_registry')
    op.drop_table('strategy_registry')
    op.drop_index(op.f('ix_self_healing_audits_path'), table_name='self_healing_audits')
    op.drop_index(op.f('ix_self_healing_audits_id'), table_name='self_healing_audits')
    op.drop_table('self_healing_audits')
    op.drop_index(op.f('ix_experiment_cohorts_strategy'), table_name='experiment_cohorts')
    op.drop_index(op.f('ix_experiment_cohorts_id'), table_name='experiment_cohorts')
    op.drop_table('experiment_cohorts')
    op.drop_index(op.f('ix_drift_history_id'), table_name='drift_history')
    op.drop_table('drift_history')
    # ### end Alembic commands ###
