from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from api.routes.auth import get_current_user
from api.utils.user_models import UserDB
from services.agent_zero.agent import base_agent_zero
from typing import Any

router = APIRouter(prefix="/zero", tags=["Agent Zero"])

@router.get("/status")
async def get_zero_status(current_user: UserDB = Depends(get_current_user)):
    """
    Returns the real-time status of the Agent Zero autonomous engine.
    """
    return {
        "is_running": base_agent_zero.is_running,
        "current_step": base_agent_zero.current_step,
        "last_run": base_agent_zero.last_run_at,
        "next_run": base_agent_zero.next_run_at,
        "integrity": "NOMINAL" if base_agent_zero.current_step != "ERROR" else "DEGRADED"
    }

@router.post("/start")
async def start_zero(background_tasks: BackgroundTasks, current_user: UserDB = Depends(get_current_user)):
    """
    Launches the autonomous director loop in the background.
    """
    if base_agent_zero.is_running:
        return {"message": "Agent Zero is already active", "status": "active"}
    
    background_tasks.add_task(base_agent_zero.start)
    return {"message": "Agent Zero Ignition Sequence Started", "status": "initializing"}

@router.post("/stop")
async def stop_zero(current_user: UserDB = Depends(get_current_user)):
    """
    Sends a halt signal to the autonomous engine.
    """
    base_agent_zero.stop()
    return {"message": "Halt Signal Received. Agent Zero stopping...", "status": "stopping"}

@router.get("/insights")
async def get_zero_insights(current_user: UserDB = Depends(get_current_user)):
    """
    Returns the latest strategy insights generated by Agent Zero.
    """
    return {
        "insights": base_agent_zero.latest_insights,
        "timestamp": base_agent_zero.last_run_at
    }
